### ISSUE TITLE
v0.10.0 of starling has not been pushed to gemcutter, only 0.9.8 is there

### ISSUE THREAD

**Issue by grempe** [starling/starling#1]
This causes a dependency problem for the new webroar app server which uses starling.

GitHub gem building and hosting has been deprecated.  GemCutter is the new official repo for the Ruby community, taking over from RubyForge.

Please see: http://webroar.lighthouseapp.com/projects/36429/tickets/5-webroar-has-dependency-on-starling-starling-gem-which-does-not-exist-on-gemcutter

Thanks.

**Comment by agibralter** [comment]
+1 :)

**Comment by joshuanapoli** [comment]
v0.9.8 (which most people will try first) doesn't work (on my mac, at least). v0.10.0, downloaded from github, works fine.

**Comment by myobie** [comment]
+1

**Comment by dustalov** [comment]
+1

**Comment by andreimaxim** [comment]
Before getting any more +1's, here's a short update: the Starling gem available from Gemcutter is basically the version from Rubyforge. Unfortunately, when Blaine and the rest of the original developers lost interest in Starling, they didn't provide the credentials for the Starling Rubyforge account so we aren't able to update that version as well.

The solution is to work with Nick Quaranto so Gemcutter will build the gem from Github, not Rubyforge. I'm not sure how easy that is, but Nick seems to be a really nice guy and I think we'll have that covered really soon, now Gemcutter is the default Rubygems host.

In the mean time, please use `xhr-starling`. It's the 0.10.0 version prepped for Gemcutter.

**Comment by grempe** [comment]
If I can provide a tip, gemcutter does not 'build' gems from either rubyforge or github.  You as the developer need to build the gem and do a 'gem push' to gemcutter.  To do this though, you will need to be listed on gemcutter as an authorized owner of the starling/starling gem on gemcutter (see 'gem help owner').

I think what you should be seeking to do is contact whoever owns the github.com/starling account, which appears to be Abdul-Rahman Advany (abdulrahman@advany.com) and requesting that you be made a collaborator on that github account so you can push changes from your fork to github.com/starling/starling (or have him pull changes into that repo).  It seems to me that if possible starling/starling should remain the canonical home of starling, and not someone's fork of that project (e.g. xhr-starling).  Otherwise you end up with a lot of confusion as to which is the canonical version (even looking at the network of forks it is by no means clear that xhr-starling would be the one to use).

Once thats taken care of, then you should be working with gemcutter, and the owner of that starling gem to add you as an 'owner' ('gem help owner') so you can push built versions of starling/starling built from the starling/starling repo to gemcutter.  Otherwise I'm not sure that Nick would have cause to add you as the owner of starling on gemcutter above any of the other multiple forks of starling.  I'm sure Nick can find the owner of the starling account that was migrated over from rubyforge and put you in touch.

My $0.02

:-)
Cheers.

**Comment by andreimaxim** [comment]
**grempe**, thanks for the ideas. I already had the commit access but I had decided to wait until I could get a hold of the owner of the Gemcutter gem.

Nick changed the owner last night so I was able to push the latest gem.

**Comment by myobie** [comment]
Thanx alot xhr.

**Comment by FooBarWidget** [comment]
Starling 0.10 is now on gemcutter so this issue can be closed.
