### ISSUE TITLE
Starling should support the flush_all command.

### ISSUE THREAD

**Issue by aselder** [starling/starling#5]
The memcache protocol supports a flush_all command. In particular the workling memcache_queue client sends this command when closing a connection. 

Even as a no-op internally, starling should support this command.

**Comment by FooBarWidget** [comment]
I've implemented this: https://github.com/FooBarWidget/starling/commit/d7ddb27714e3909a5938f099ee10c0db4a65935b

**Comment by FooBarWidget** [comment]
Looks like the patch has been accepted upstream. This issue can be closed.

**Comment by dharmarth** [comment]
Sorry forgot to revert back here.
